---
abstract: 'be like TOBYINK and use these Packaging stuffz'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Task::BeLike::TOBYINK::Packaging
name: Task-BeLike-TOBYINK-Packaging
no_index:
  directory:
    - inc
    - xt
requires:
  Module::Package::RDF: 0
  Perl::Version: 0
  RT::ClientX::GrabBugs: 0
  XT::Manager: 0
  XT::Util: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Task-BeLike-TOBYINK-Packaging
  homepage: https://metacpan.org/release/Task-BeLike-TOBYINK-Packaging
  license: http://dev.perl.org/licenses/
version: 2012.276
